name: Test3

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
    - name: Test1
      run: |
        cd /home/runner
        lscpu
    - name: Test2
      run: |
        cd /home/runner
        free -m
    - name: Test3
      run: |
        cd /home/runner
        df
